/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package programa;

/**
 *
 * @author Kris
 */
public class Neyra extends javax.swing.JPanel {

    /**
     * Creates new form Neyra
     */
    public Neyra() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(18, 102, 126));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Neyra (1).jpg"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("MS UI Gothic", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Samantha Neyra Marquez");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("<html>Samantha es una chica de 19 años que tiene muchos gustos y hobbies. Le gusta hacer postres, escuchar música, ver películas y navegar en plataformas digitales.  Hacer postres es una de sus pasiones, y le encanta preparar diferentes dulces y tartas para sus seres queridos. Le gusta probar nuevas recetas y sabores, y siempre está buscando mejorar sus habilidades culinarias. Su postre favorito es la tarta de queso con frutos rojos.  Escuchar música es otra de sus actividades favoritas, y le gusta disfrutar de diferentes estilos y artistas. Algunos de sus favoritos son Ariana Grande, Dua Lipa, Harry Styles y Bad Bunny. También le gusta bailar y cantar, y a veces hace covers de sus canciones preferidas.  Ver películas es una forma de relajarse y divertirse para Samantha. Le gustan las películas de comedia, romance, acción y terror, y siempre está al día de los últimos estrenos. Algunas de sus películas favoritas son La La Land, Avengers: Endgame, It y The Conjuring.  Navegar en plataformas digitales es una manera de estar conectada y entretenida para Samantha. Le gusta usar redes sociales como Instagram, TikTok y YouTube, donde sigue a sus influencers y creadores de contenido favoritos. También le gusta usar plataformas de streaming como Netflix, Disney+ y Spotify, donde ve series, películas y escucha música.<html>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel1)
                        .addGap(171, 171, 171)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 772, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(6152, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(145, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(35, 35, 35))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
