/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package programa;

import java.awt.BorderLayout;

/**
 *
 * @author Kris
 */
public class ventana3 extends javax.swing.JFrame {

    /**
     * Creates new form ventana3
     */
    public ventana3() {
        initComponents();
        
        Cardenas car = new Cardenas();
        car.setSize(1440,560);
        car.setLocation(0, 0);
        content.removeAll();
        content.add(car, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Regresar = new javax.swing.JButton();
        Cardenas = new javax.swing.JButton();
        Cartagena = new javax.swing.JButton();
        Jesusi = new javax.swing.JButton();
        Neyra = new javax.swing.JButton();
        Ramos = new javax.swing.JButton();
        content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1920, 1080));

        jPanel1.setBackground(new java.awt.Color(18, 102, 126));

        Regresar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Volver_64.png"))); // NOI18N
        Regresar.setText("Regresar");
        Regresar.setContentAreaFilled(false);
        Regresar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Regresar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Volver_64.png"))); // NOI18N
        Regresar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Volver_96.png"))); // NOI18N
        Regresar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });

        Cardenas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Cardenas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Men_64.png"))); // NOI18N
        Cardenas.setText("Kris");
        Cardenas.setContentAreaFilled(false);
        Cardenas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Cardenas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Cardenas.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Men_64.png"))); // NOI18N
        Cardenas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Men_96.png"))); // NOI18N
        Cardenas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Cardenas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CardenasActionPerformed(evt);
            }
        });

        Cartagena.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Cartagena.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Men_64.png"))); // NOI18N
        Cartagena.setText("Pyro");
        Cartagena.setContentAreaFilled(false);
        Cartagena.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Cartagena.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Men_64.png"))); // NOI18N
        Cartagena.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Men_96.png"))); // NOI18N
        Cartagena.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Cartagena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CartagenaActionPerformed(evt);
            }
        });

        Jesusi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Jesusi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Woman_64.png"))); // NOI18N
        Jesusi.setText("Marycielo");
        Jesusi.setContentAreaFilled(false);
        Jesusi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Jesusi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Jesusi.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Woman_64.png"))); // NOI18N
        Jesusi.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Woman_96.png"))); // NOI18N
        Jesusi.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Jesusi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JesusiActionPerformed(evt);
            }
        });

        Neyra.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Neyra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Woman_64.png"))); // NOI18N
        Neyra.setText("Samantha");
        Neyra.setContentAreaFilled(false);
        Neyra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Neyra.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Neyra.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Woman_64.png"))); // NOI18N
        Neyra.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Woman_96.png"))); // NOI18N
        Neyra.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Neyra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NeyraActionPerformed(evt);
            }
        });

        Ramos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Ramos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Woman_64.png"))); // NOI18N
        Ramos.setText("Alessandra");
        Ramos.setContentAreaFilled(false);
        Ramos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Ramos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Ramos.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Woman_64.png"))); // NOI18N
        Ramos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Woman_96.png"))); // NOI18N
        Ramos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Ramos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RamosActionPerformed(evt);
            }
        });

        content.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1440, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(Cardenas, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(189, 189, 189)
                            .addComponent(Jesusi, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Neyra, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(228, 228, 228)
                            .addComponent(Ramos, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(207, 207, 207)
                            .addComponent(Cartagena, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(content, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Neyra, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(Cardenas, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Ramos, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cartagena, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jesusi, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
       Proyecto inicio = new Proyecto();
        inicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RegresarActionPerformed

    private void CardenasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CardenasActionPerformed
       Cardenas car = new Cardenas();
        car.setSize(1440,560);
        car.setLocation(0, 0);
        content.removeAll();
        content.add(car, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_CardenasActionPerformed

    private void CartagenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CartagenaActionPerformed
       Cartagena car = new Cartagena();
        car.setSize(1440,560);
        car.setLocation(0, 0);
        content.removeAll();
        content.add(car, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_CartagenaActionPerformed

    private void JesusiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JesusiActionPerformed
        Jesusi car = new Jesusi();
        car.setSize(1440,560);
        car.setLocation(0, 0);
        content.removeAll();
        content.add(car, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_JesusiActionPerformed

    private void NeyraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NeyraActionPerformed
      Neyra car = new Neyra();
        car.setSize(1440,560);
        car.setLocation(0, 0);
        content.removeAll();
        content.add(car, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_NeyraActionPerformed

    private void RamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RamosActionPerformed
       Ramos car = new Ramos();
        car.setSize(1440,560);
        car.setLocation(0, 0);
        content.removeAll();
        content.add(car, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_RamosActionPerformed


    
          
          public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventana3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cardenas;
    private javax.swing.JButton Cartagena;
    private javax.swing.JButton Jesusi;
    private javax.swing.JButton Neyra;
    private javax.swing.JButton Ramos;
    private javax.swing.JButton Regresar;
    private javax.swing.JPanel content;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private static class content {
 
       

        public content() {
            
        
        }
    }
}
