/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package programa;

/**
 *
 * @author USER
 */
public class vent1_pg4_tAlcance extends javax.swing.JPanel {

    double cj_Distancia,cj_VelocidadA,cj_VelocidadB,Resultado;
    public vent1_pg4_tAlcance() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel_Content_pg1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cjText1_Distancia = new javax.swing.JTextField();
        cjText1_VelocidadA = new javax.swing.JTextField();
        cjText1_VelocidadB = new javax.swing.JTextField();
        cjText1_RESULTADO = new javax.swing.JTextField();
        CALCULAR_tAlcance = new javax.swing.JButton();
        BORRAR_tAlcance = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(18, 31, 44));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_Content_pg1.setBackground(new java.awt.Color(79, 136, 148));
        jPanel_Content_pg1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("MS UI Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Ingrese Distancia");
        jPanel_Content_pg1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 320, 50));

        jLabel2.setFont(new java.awt.Font("MS UI Gothic", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Ingrese Velocidad del movil A");
        jPanel_Content_pg1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 320, 50));

        jLabel3.setFont(new java.awt.Font("MS UI Gothic", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Ingrese Velocidad del movil B");
        jPanel_Content_pg1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 320, 50));

        jLabel4.setFont(new java.awt.Font("MS UI Gothic", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Resultado ");
        jPanel_Content_pg1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 490, 320, 50));

        cjText1_Distancia.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        cjText1_Distancia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cjText1_Distancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cjText1_DistanciaActionPerformed(evt);
            }
        });
        jPanel_Content_pg1.add(cjText1_Distancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, 110, 80));

        cjText1_VelocidadA.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        cjText1_VelocidadA.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cjText1_VelocidadA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cjText1_VelocidadAActionPerformed(evt);
            }
        });
        jPanel_Content_pg1.add(cjText1_VelocidadA, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 110, 80));

        cjText1_VelocidadB.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        cjText1_VelocidadB.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cjText1_VelocidadB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cjText1_VelocidadBActionPerformed(evt);
            }
        });
        jPanel_Content_pg1.add(cjText1_VelocidadB, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 340, 110, 80));

        cjText1_RESULTADO.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        cjText1_RESULTADO.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cjText1_RESULTADO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cjText1_RESULTADOActionPerformed(evt);
            }
        });
        jPanel_Content_pg1.add(cjText1_RESULTADO, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 480, 160, 80));

        CALCULAR_tAlcance.setBackground(new java.awt.Color(51, 255, 51));
        CALCULAR_tAlcance.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        CALCULAR_tAlcance.setText("CALCULAR");
        CALCULAR_tAlcance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CALCULAR_tAlcanceActionPerformed(evt);
            }
        });
        jPanel_Content_pg1.add(CALCULAR_tAlcance, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 440, 210, 60));

        BORRAR_tAlcance.setBackground(new java.awt.Color(255, 0, 0));
        BORRAR_tAlcance.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BORRAR_tAlcance.setText("BORRAR");
        BORRAR_tAlcance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BORRAR_tAlcanceActionPerformed(evt);
            }
        });
        jPanel_Content_pg1.add(BORRAR_tAlcance, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 540, 210, 60));

        jPanel1.add(jPanel_Content_pg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 960, 650));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1140, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cjText1_DistanciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cjText1_DistanciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cjText1_DistanciaActionPerformed

    private void cjText1_VelocidadAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cjText1_VelocidadAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cjText1_VelocidadAActionPerformed

    private void cjText1_VelocidadBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cjText1_VelocidadBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cjText1_VelocidadBActionPerformed

    private void cjText1_RESULTADOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cjText1_RESULTADOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cjText1_RESULTADOActionPerformed

    private void CALCULAR_tAlcanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CALCULAR_tAlcanceActionPerformed
        cj_Distancia=Double.parseDouble(cjText1_Distancia.getText());
        cj_VelocidadA=Double.parseDouble(cjText1_VelocidadA.getText());
        cj_VelocidadB=Double.parseDouble(cjText1_VelocidadB.getText());
        Resultado=cj_Distancia/(cj_VelocidadA-cj_VelocidadB);

        //Velocidad Media=posicionfinal-PosicionInicial/tiempo
        cjText1_RESULTADO.setText(String.valueOf(Resultado));
    }//GEN-LAST:event_CALCULAR_tAlcanceActionPerformed

    private void BORRAR_tAlcanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BORRAR_tAlcanceActionPerformed
        cjText1_Distancia.setText(""); 
        cjText1_VelocidadA.setText("");
        cjText1_VelocidadB.setText("");
        cjText1_RESULTADO.setText("");
    }//GEN-LAST:event_BORRAR_tAlcanceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BORRAR_tAlcance;
    private javax.swing.JButton CALCULAR_tAlcance;
    private javax.swing.JTextField cjText1_Distancia;
    private javax.swing.JTextField cjText1_RESULTADO;
    private javax.swing.JTextField cjText1_VelocidadA;
    private javax.swing.JTextField cjText1_VelocidadB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_Content_pg1;
    // End of variables declaration//GEN-END:variables
}
