/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package programa;

/**
 *
 * @author USER
 */
public class vent2_pg5_AceleracionMed extends javax.swing.JPanel {

    double cj_VelocidadInicial,cj_VelocidadFinal,cj_TiempoInicial,cj_TiempoFinal,Resultado;
    public vent2_pg5_AceleracionMed() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel_Content_pg2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cjText2_VelocidadInicial = new javax.swing.JTextField();
        cjText2_VelocidadFinal = new javax.swing.JTextField();
        cjText2_TiempoFinal = new javax.swing.JTextField();
        cjText2_RESULTADO = new javax.swing.JTextField();
        CALCULAR_AceleracionMed = new javax.swing.JButton();
        BORRAR_AceleracionMed = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cjText2_TiempoInicial = new javax.swing.JTextField();

        jPanel2.setBackground(new java.awt.Color(18, 31, 44));

        jPanel_Content_pg2.setBackground(new java.awt.Color(79, 136, 148));
        jPanel_Content_pg2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("MS UI Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Ingrese Velocidad Inicial ");
        jPanel_Content_pg2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 320, 50));

        jLabel2.setFont(new java.awt.Font("MS UI Gothic", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Ingrese Velocidad Final");
        jPanel_Content_pg2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 320, 50));

        jLabel3.setFont(new java.awt.Font("MS UI Gothic", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Ingrese Tiempo Final");
        jPanel_Content_pg2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 320, 50));

        jLabel4.setFont(new java.awt.Font("MS UI Gothic", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Resultado ");
        jPanel_Content_pg2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 490, 320, 50));

        cjText2_VelocidadInicial.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        cjText2_VelocidadInicial.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cjText2_VelocidadInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cjText2_VelocidadInicialActionPerformed(evt);
            }
        });
        jPanel_Content_pg2.add(cjText2_VelocidadInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 110, 80));

        cjText2_VelocidadFinal.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        cjText2_VelocidadFinal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cjText2_VelocidadFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cjText2_VelocidadFinalActionPerformed(evt);
            }
        });
        jPanel_Content_pg2.add(cjText2_VelocidadFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 110, 80));

        cjText2_TiempoFinal.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        cjText2_TiempoFinal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cjText2_TiempoFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cjText2_TiempoFinalActionPerformed(evt);
            }
        });
        jPanel_Content_pg2.add(cjText2_TiempoFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, 110, 80));

        cjText2_RESULTADO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cjText2_RESULTADOActionPerformed(evt);
            }
        });
        jPanel_Content_pg2.add(cjText2_RESULTADO, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 480, 160, 80));

        CALCULAR_AceleracionMed.setBackground(new java.awt.Color(51, 255, 51));
        CALCULAR_AceleracionMed.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        CALCULAR_AceleracionMed.setText("CALCULAR");
        CALCULAR_AceleracionMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CALCULAR_AceleracionMedActionPerformed(evt);
            }
        });
        jPanel_Content_pg2.add(CALCULAR_AceleracionMed, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 440, 210, 60));

        BORRAR_AceleracionMed.setBackground(new java.awt.Color(255, 0, 0));
        BORRAR_AceleracionMed.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BORRAR_AceleracionMed.setText("BORRAR");
        BORRAR_AceleracionMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BORRAR_AceleracionMedActionPerformed(evt);
            }
        });
        jPanel_Content_pg2.add(BORRAR_AceleracionMed, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 540, 210, 60));

        jLabel6.setFont(new java.awt.Font("MS UI Gothic", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Ingrese Tiempo Inicial");
        jPanel_Content_pg2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 320, 50));

        cjText2_TiempoInicial.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        cjText2_TiempoInicial.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cjText2_TiempoInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cjText2_TiempoInicialActionPerformed(evt);
            }
        });
        jPanel_Content_pg2.add(cjText2_TiempoInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, 110, 80));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1140, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel_Content_pg2, javax.swing.GroupLayout.PREFERRED_SIZE, 960, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel_Content_pg2, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cjText2_VelocidadInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cjText2_VelocidadInicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cjText2_VelocidadInicialActionPerformed

    private void cjText2_VelocidadFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cjText2_VelocidadFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cjText2_VelocidadFinalActionPerformed

    private void cjText2_TiempoFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cjText2_TiempoFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cjText2_TiempoFinalActionPerformed

    private void cjText2_RESULTADOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cjText2_RESULTADOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cjText2_RESULTADOActionPerformed

    private void CALCULAR_AceleracionMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CALCULAR_AceleracionMedActionPerformed
        cj_VelocidadInicial=Double.parseDouble(cjText2_VelocidadInicial.getText());
        cj_VelocidadFinal=Double.parseDouble(cjText2_VelocidadFinal.getText());
        cj_TiempoInicial=Double.parseDouble(cjText2_TiempoInicial.getText());
        cj_TiempoFinal=Double.parseDouble(cjText2_TiempoFinal.getText());

        //VelocidadMedia= (VelocidadFinal - velocidad Inicial) / (tiempoFinal - TiempoInicial)
        Resultado=(cj_VelocidadFinal-cj_VelocidadInicial)/(cj_TiempoFinal-cj_TiempoInicial);
       
        cjText2_RESULTADO.setText(String.valueOf(Resultado));
    }//GEN-LAST:event_CALCULAR_AceleracionMedActionPerformed

    private void BORRAR_AceleracionMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BORRAR_AceleracionMedActionPerformed
        cjText2_VelocidadInicial.setText("");
        cjText2_VelocidadFinal.setText("");
        cjText2_TiempoInicial.setText("");
        cjText2_TiempoFinal.setText("");
        cjText2_RESULTADO.setText("");
    }//GEN-LAST:event_BORRAR_AceleracionMedActionPerformed

    private void cjText2_TiempoInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cjText2_TiempoInicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cjText2_TiempoInicialActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BORRAR_AceleracionMed;
    private javax.swing.JButton CALCULAR_AceleracionMed;
    private javax.swing.JTextField cjText2_RESULTADO;
    private javax.swing.JTextField cjText2_TiempoFinal;
    private javax.swing.JTextField cjText2_TiempoInicial;
    private javax.swing.JTextField cjText2_VelocidadFinal;
    private javax.swing.JTextField cjText2_VelocidadInicial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel_Content_pg2;
    // End of variables declaration//GEN-END:variables
}
