/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package programa;

/**
 *
 * @author USER
 */
public class vent1_pg2_VelocidadMed extends javax.swing.JPanel {

   Double cj_PosInicial,cj_PosFinal,cj_Tiempo,Resultado;
    public vent1_pg2_VelocidadMed() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jPanel_Content_pg1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cjText1_PosInicial = new javax.swing.JTextField();
        cjText1_PosFinal = new javax.swing.JTextField();
        cjText1_Tiempo = new javax.swing.JTextField();
        cjText1_RESULTADO = new javax.swing.JTextField();
        CALCULAR_VelocidadMed = new javax.swing.JButton();
        BORRAR_VelocidadMed = new javax.swing.JButton();

        jLabel6.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel6.setText("RESPUESTA");

        setBackground(new java.awt.Color(18, 31, 44));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_Content_pg1.setBackground(new java.awt.Color(79, 136, 148));
        jPanel_Content_pg1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("MS UI Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Ingrese Posicion Inicial ");
        jPanel_Content_pg1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 320, 50));

        jLabel2.setFont(new java.awt.Font("MS UI Gothic", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Ingrese Posicion Final");
        jPanel_Content_pg1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 320, 50));

        jLabel3.setFont(new java.awt.Font("MS UI Gothic", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Ingrese Tiempo");
        jPanel_Content_pg1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 320, 50));

        jLabel4.setFont(new java.awt.Font("MS UI Gothic", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Resultado ");
        jPanel_Content_pg1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 490, 320, 50));

        cjText1_PosInicial.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        cjText1_PosInicial.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cjText1_PosInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cjText1_PosInicialActionPerformed(evt);
            }
        });
        jPanel_Content_pg1.add(cjText1_PosInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 110, 80));

        cjText1_PosFinal.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        cjText1_PosFinal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cjText1_PosFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cjText1_PosFinalActionPerformed(evt);
            }
        });
        jPanel_Content_pg1.add(cjText1_PosFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 110, 80));

        cjText1_Tiempo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        cjText1_Tiempo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cjText1_Tiempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cjText1_TiempoActionPerformed(evt);
            }
        });
        jPanel_Content_pg1.add(cjText1_Tiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, 110, 80));

        cjText1_RESULTADO.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        cjText1_RESULTADO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cjText1_RESULTADOActionPerformed(evt);
            }
        });
        jPanel_Content_pg1.add(cjText1_RESULTADO, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 480, 160, 80));

        CALCULAR_VelocidadMed.setBackground(new java.awt.Color(51, 255, 51));
        CALCULAR_VelocidadMed.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        CALCULAR_VelocidadMed.setText("CALCULAR");
        CALCULAR_VelocidadMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CALCULAR_VelocidadMedActionPerformed(evt);
            }
        });
        jPanel_Content_pg1.add(CALCULAR_VelocidadMed, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 440, 210, 60));

        BORRAR_VelocidadMed.setBackground(new java.awt.Color(255, 0, 0));
        BORRAR_VelocidadMed.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BORRAR_VelocidadMed.setText("BORRAR");
        BORRAR_VelocidadMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BORRAR_VelocidadMedActionPerformed(evt);
            }
        });
        jPanel_Content_pg1.add(BORRAR_VelocidadMed, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 540, 210, 60));

        add(jPanel_Content_pg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 960, 650));
    }// </editor-fold>//GEN-END:initComponents

    private void cjText1_PosInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cjText1_PosInicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cjText1_PosInicialActionPerformed

    private void cjText1_PosFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cjText1_PosFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cjText1_PosFinalActionPerformed

    private void cjText1_TiempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cjText1_TiempoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cjText1_TiempoActionPerformed

    private void cjText1_RESULTADOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cjText1_RESULTADOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cjText1_RESULTADOActionPerformed

    private void CALCULAR_VelocidadMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CALCULAR_VelocidadMedActionPerformed
       cj_PosInicial=Double.parseDouble(cjText1_PosInicial.getText());
       cj_PosFinal=Double.parseDouble(cjText1_PosFinal.getText());
       cj_Tiempo=Double.parseDouble(cjText1_Tiempo.getText());
       Resultado=(cj_PosFinal-cj_PosInicial)/cj_Tiempo;
        
        //Velocidad Media=posicionfinal-PosicionInicial/tiempo
        cjText1_RESULTADO.setText(String.valueOf(Resultado));
        
    }//GEN-LAST:event_CALCULAR_VelocidadMedActionPerformed

    private void BORRAR_VelocidadMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BORRAR_VelocidadMedActionPerformed
        cjText1_PosInicial.setText(""); 
        cjText1_PosFinal.setText("");
        cjText1_Tiempo.setText("");
        cjText1_RESULTADO.setText("");
    }//GEN-LAST:event_BORRAR_VelocidadMedActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BORRAR_VelocidadMed;
    private javax.swing.JButton CALCULAR_VelocidadMed;
    private javax.swing.JTextField cjText1_PosFinal;
    private javax.swing.JTextField cjText1_PosInicial;
    private javax.swing.JTextField cjText1_RESULTADO;
    private javax.swing.JTextField cjText1_Tiempo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel_Content_pg1;
    // End of variables declaration//GEN-END:variables
}
